driver: net: Nuke unused code
* Fix following error

../../../../../../kernel/google/msm-4.14/drivers/net/usb/usbnet.c:2300:6: error: unused variable 'i' [-Werror,-Wunused-variable]
        int i = 0;
            ^
1 error generated.